name: dalle
channels:
  - rmg
  - conda-forge
  - rdkit
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.6.20=hecda079_0
  - cffi=1.15.0=py38h3931269_0
  - cpuonly=2.0=0
  - cudatoolkit=10.1.243=h036e899_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py38h578d9bd_4
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=12_linux64_mkl
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.4=h780b84a_0
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - ncurses=6.2=h58526e2_4
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_1
  - numpy-base=1.21.2=py38h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=3.0.0=h7f98852_2
  - pip=21.3.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - python=3.8.12=hf930737_2_cpython
  - python_abi=3.8=2_cp38
  - pytorch-mutex=1.0=cpu
  - readline=8.1=h46c0cb4_0
  - ruamel_yaml=0.15.80=py38h497a2fe_1006
  - setuptools=60.2.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.11=h27826a3_1
  - torchaudio=0.10.0=py38_cpu
  - typing_extensions=4.0.1=pyha770c72_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - ansicolors==1.1.8
    - antlr4-python3-runtime==4.8
    - anyio==3.4.0
    - apptools==5.1.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astroid==2.9.3
    - async-timeout==4.0.2
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - blessings==1.7
    - cachetools==4.2.4
    - certifi==2021.10.8
    - charset-normalizer==2.0.9
    - click==8.0.3
    - cloudpickle==2.0.0
    - configobj==5.0.6
    - cycler==0.11.0
    - cython==0.29.26
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - einops==0.3.2
    - entrypoints==0.3
    - envisage==6.0.1
    - filelock==3.4.2
    - fonttools==4.28.5
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - ftfy==6.0.3
    - fvcore==0.1.5.post20211023
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - gpustat==0.6.0
    - grpcio==1.43.0
    - huggingface-hub==0.0.12
    - idna==3.3
    - imageio==2.13.5
    - importlib-metadata==4.10.0
    - importlib-resources==5.4.0
    - iopath==0.1.9
    - ipykernel==6.6.0
    - ipython==7.30.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - isort==5.10.1
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.3.2
    - jupyter-client==7.1.0
    - jupyter-core==4.9.1
    - jupyter-server==1.13.1
    - jupyterlab==3.2.5
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - lazy-object-proxy==1.7.1
    - llvmlite==0.38.0
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - mock==4.0.3
    - multidict==5.2.0
    - nbclassic==0.3.4
    - nbclient==0.5.9
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - nibabel==3.2.2
    - notebook==6.4.6
    - numba==0.55.0
    - numpy==1.21.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pandas==1.4.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - platformdirs==2.4.1
    - portalocker==2.3.2
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.24
    - protobuf==3.19.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0
    - pydeprecate==0.3.1
    - pydicom==2.2.2
    - pydot==1.4.2
    - pyface==7.4.0
    - pyflakes==2.4.0
    - pygments==2.11.0
    - pylint==2.12.2
    - pynndescent==0.5.6
    - pyparsing==3.0.6
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.1
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - python-magic==0.4.25
    - pytorch-lightning==1.5.7
    - pytorch-pretrained-vit==0.0.7
    - pytz==2021.3
    - pywavelets==1.2.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - regex==2021.11.10
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - ruamel-yaml-clib==0.2.6
    - sacremoses==0.0.47
    - scikit-image==0.19.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sniffio==1.2.0
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tifffile==2021.11.2
    - timm==0.4.9
    - tokenizers==0.10.3
    - toml==0.10.2
    - torch==1.10.0
    - torchmetrics==0.6.2
    - torchvision==0.13.0a0+7bb5e41
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.1
    - traits==6.3.2
    - traitsui==7.2.1
    - transformers==4.8.1
    - triton==1.1.1
    - umap-learn==0.5.2
    - urllib3==1.26.7
    - vtk==9.1.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - werkzeug==2.0.2
    - widgetsnbextension==3.5.2
    - wrapt==1.13.3
    - wslink==1.4.1
    - yacs==0.1.8
    - yarl==1.7.2
    - zipp==3.7.0
prefix: ANONYMOUS_ROOTDIR/develop/miniconda3/envs/dalle
